name: ThePhotoHour
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9316913727670908
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e8e2d6'
    - '#000501'
    - '#8ababc'
    - '#ff8400'
    - '#9b6400'
  brandStrength: 0
  lightness: 0.3816238970030099
  saturation: 0.3125
  rhythmicContrast: 0
purpose: []
